### ISSUE TITLE
Suppress map card in the absence of US territory representation

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#816] opened 2021-05-11 21:02 UTC
Currently, Vega does not support displaying information for US territories.

Until progress is made on #815, we want to hide the map card.

**Comment by vanshkumar** [comment] 2021-05-11 23:36
Hey Elizabeth, is this a dupe of #760 ?

**Comment by kkatzen** [comment] 2021-05-13 19:08
We sure make sure that when we hide the map card, the paired charts still line up in compare views

**Comment by kkatzen** [comment] 2021-05-14 22:14
Does https://github.com/SatcherInstitute/health-equity-tracker/pull/853 deprecate this issue?

**Comment by vanshkumar** [comment] 2021-05-14 22:18
Yes, I believe so

**Comment by vanshkumar** [comment] 2021-05-16 02:59
Closing as #853 fixed this

**Closed by vanshkumar** 2021-05-16 02:59 UTC
