### ISSUE TITLE
Frontend linter

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#711] opened 2021-04-29 20:44 UTC
At Krista's suggestion: Finding a frontend linter.

**Comment by kkatzen** [comment] 2021-04-29 21:43
What exactly does this refer to? I've suggested we each use a linter in our own IDEs. Aaron and I both did this so our changes are automatically linted when we commit. Is this bug to add one to the repo?

**Comment by aaronsn** [comment] 2021-04-30 00:42
I think this is a dupe of https://github.com/SatcherInstitute/health-equity-tracker/issues/245. Ideally we set up the linter on the project so that the PR checks will enforce it even if devs don't have it set up in their own IDE

**Closed** 2022-07-08 01:59 UTC
