### ISSUE TITLE
Covid Tracking Project: Exclude states that don't report a metric from population totals when comparing to population

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#208] opened 2020-12-17 20:14 UTC
For instance, for the USA and Covid, we're showing the race breakdowns for the entire USA and comparing them against Covid, instead we should compare the breakdowns for those states only

**Comment by kkatzen** [comment] 2021-01-15 19:25
for the disparity bar chart when it shows ’vs. Population” the population totals are for the entire USA, when you can see on the map we only have COVID data for only 6 states. so instead of vs Population showing the race breakdowns for all 50 states we want to only show it for those 6 states which had covid data

we may also want to have a UI element indicating what "population" represents

**Comment by aaronsn** [comment] 2021-02-01 19:00
This still needs more work to actually be fixed. Specifically, the `[metric]_reporting_population` columns need to be populated correctly. I briefly looked into doing this on the frontend and I think it's too complex. The backend should create these columns by joining with ACS at the state level, and then summing across the states to get the national level data.

**Comment by aaronsn** [comment] 2021-02-26 16:45
Discussed with Jennie, she's going to work on doing this on the backend.

These are the column names we're expecting the dataset to have:

https://github.com/SatcherInstitute/health-equity-tracker/blob/6f523bf1707aa014d854332843800ee060342a31/frontend/src/data/variables/CovidProvider.ts#L30-L35

For states, the population values will just be the state's population. For the national level, the population values will be the sum of the population of states that report the relevant metric (cases/deaths/hosp)

**Comment by vanshkumar** [comment] 2021-03-16 21:14
Not needed anymore, marking as dupe of #147

**Closed by vanshkumar** 2021-03-16 21:14 UTC
Labels: frontend, high priority
