### ISSUE TITLE
Frontend changes to support ACS population schema changes

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#340] opened 2021-01-29 03:13 UTC
See https://github.com/SatcherInstitute/health-equity-tracker/issues/339 for context. race_and_ethnicity is changing to race and another column that indicates whether it includes hispanic/latino.

The frontend relies on the `race_and_ethnicity` column in a number of places. We will either need to do an audit of usages or generate a race_and_ethnicity column to continue using.

**Comment by vanshkumar** [comment] 2021-03-20 00:22
Dupe of #307

**Closed by vanshkumar** 2021-03-20 00:22 UTC
Labels: frontend
