### ISSUE TITLE
Replace Vega library with one that supports US territories

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#815] opened 2021-05-11 21:01 UTC
Currently, Vega does not support displaying information from US territories. 

We want to either amend Vega to support this (nontrivial; not recommended) or find another library that does support displaying US territories (preferred).

**Comment by aaronsn** [comment] 2021-05-13 00:51
I don't think this is inherent to Vega, I think it's just the geography dataset we're using

**Comment by efregoso** [comment] 2021-05-13 23:19
I think our most recent datasets do include data from US territories.  IIRC
from one of our syncs, they are being displayed in tables and other cards
where they show up but not in the mapcard.  @Vansh?

**Comment by aaronsn** [comment] 2021-05-13 23:54
By "geography dataset" I meant the dataset that defines the outlines of the states/counties. The one we're using is here: https://github.com/SatcherInstitute/health-equity-tracker/blob/master/frontend/public/counties-10m.json.

The Vega library doesn't have the geographies built-in, we provide our own geographies. Not sure where @kkatzen got the one we have from but I'm sure we can find another one that has territories.

Krista can confirm or correct if I've misstated anything here ^

**Comment by kkatzen** [comment] 2021-05-14 20:21
I think this is a dupe of #210
See more information about the issue here: https://gis.stackexchange.com/questions/366189/how-to-show-puerto-rico-in-albersusa-projection-in-vega-lite-or-vega

**Comment by kkatzen** [comment] 2021-05-14 20:22
This could be a solution: https://www.npmjs.com/package/geo-albers-usa-territories

**Comment by joshzarrabi** [comment] 2021-06-08 00:09
Another option we discussed was switching the national map to a hex based map. Another benefit to this choice would be to show each state as the same size, which is a bit more equitable.

**Comment by kkatzen** [comment] 2021-06-10 18:56
I will try to get a demo where we have additional submaps to show the territories on the national level and we'll see how we like it

**Comment by kkatzen** [comment] 2021-07-02 21:04
Territory circles were added to national level here: https://github.com/SatcherInstitute/health-equity-tracker/pull/988
With this change, I think we should close this bug and just stick with vega personally

**Comment by benhammondmusic** [comment] 2021-08-17 21:31
@joshzarrabi can we close this is is replacing the territory circled with their actual shapes on the national map still in consideration? I agree with @kkatzen we can close this

**Comment by joshzarrabi** [comment] 2021-08-18 13:47
Lets close it! Thanks :)

**Closed by joshzarrabi** 2021-08-18 13:47 UTC
