### ISSUE TITLE
Testing coverage

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#241] opened 2020-10-16 02:08 UTC
We likely won't have great coverage early on due to prototyping and quickly iterating - we should go back and make sure we have coverage for key pieces of code.

Also might be worth having some more integration-ey tests that work with more end-to-end flows

**Comment by vanshkumar** [comment] 2021-03-20 01:53
Dupe of #88

**Closed by vanshkumar** 2021-03-20 01:53 UTC
Labels: frontend
