### ISSUE TITLE
Our Team format

### ISSUE THREAD

**Issue by achipham** [SatcherInstitute/health-equity-tracker#829] opened 2021-05-13 18:39 UTC
Leadership Team -
can we change it to 5 people in first row, 5 in the second row (instead of 6 and 4)

<img width="1447" alt="Screen Shot 2021-05-13 at 8 39 12 AM" src="https://user-images.githubusercontent.com/31259975/118171136-b4042880-b3c6-11eb-9674-5d5f5b353893.png">

**Comment by vanshkumar** [comment] 2021-05-13 21:42
I think this is a dupe of #752, so gonna close this one :)

**Closed by vanshkumar** 2021-05-13 21:42 UTC
