### ISSUE TITLE
Show Top X of subregion map in cases per 100k

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#757] opened 2021-05-06 16:28 UTC
### Problem

If the user wants to compare which counties have the most cases of COVID in their state, the current workflow is to hover over each county and take a note/screenshot of the hover text.There is no way to display multiple at once or intuitively see which states are best/worst (especially if color shade is the same).

For example,  in the following image, it is difficult to pinpoint the worst counties without hovering over all the green ones.

![Screen Shot 2021-05-06 at 12 26 13 PM](https://user-images.githubusercontent.com/3689026/117332826-49069f00-ae66-11eb-8882-609f7aa1c8a2.png)

### Request

Add a toggle on the map to “Show Top X of [Counties/States] with the highest incidences of Cases per 100k. Clicking the toggle will only highlight the top X.

### Additional comments / risks

Consider Wording - Top vs Best vs Bottom  …. Top is actually the worst geography? Can we include toggle for best and worst?

Top X - originally discussed as Top 5. Good? Or Top 10? Or both with a toggle? (too many toggles)?

Risking information overload

**Comment by vanshkumar** [comment] 2021-05-13 21:13
The main work is done here, leaving it open in backlog to discuss how we want the highlighting to work post-launch

**Comment by vanshkumar** [comment] 2021-05-13 21:39
Actually this seems like a dupe of #826, going to close this one and move the other one to the backlog (as the other issue has more details)

**Closed by vanshkumar** 2021-05-13 21:39 UTC
