### ISSUE TITLE
Integrate metadata from data server to populate data downloads page

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#237] opened 2020-10-14 20:22 UTC
We need to create a class for dataset metadata type
https://docs.google.com/document/d/1viK-Z8J2Y92ZaM4SqxUiylQiwkVsTfarjVeTH4LkTww/edit#

**Comment by aaronsn** [comment] 2021-01-13 17:06
Duplicate of #264

**Closed by aaronsn** 2021-01-13 17:06 UTC
Labels: frontend
